### ISSUE TITLE
Looks a lot like Enaml (Python)

### ISSUE THREAD

**Issue by Kochise** [mdavisprog/OctaneGUI#1]
Look at an example file :

https://github.com/nucleic/enaml/blob/main/examples/layout/advanced/manual_vbox.enaml

I've documented the object tree :

https://github.com/Kochise/enaml-studio/blob/main/enaml-api.py

Good luck.

**Comment by mdavisprog** [comment]
Hi, thanks for showing this project. I was inspired by how Godot handles their control tree:

[https://docs.godotengine.org/en/stable/classes/class_container.html](https://docs.godotengine.org/en/stable/classes/class_container.html)

It's good to see this similar concept used on other projects. Good luck to you as well.
