### ISSUE TITLE
Compilation error Clang 15.0.7

### ISSUE THREAD

**Issue by seb777** [mdavisprog/OctaneGUI#17]
I use the linux OS (archlinux x86_64) with the Clang compiler:

-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
Desired windowing library: SDL2
Desired rendering library: OpenGL

1- First, I get the following compilation error:
```
/home/seb/Projets/OctaneGUI/Source/OctaneGUI/Controls/Splitter.cpp:385:16: error: variable 'Index' set but not used [-Werror,-Wunused-but-set-variable]
        size_t Index = 0;
               ^
1 error generated.
make[2]: *** [Source/OctaneGUI/CMakeFiles/OctaneGUI.dir/build.make:454: Source/OctaneGUI/CMakeFiles/OctaneGUI.dir/Controls/Splitter.cpp.o] Error 1
```

2- I removed variable 'Index' in Splitter.cpp. Then:
```
In file included from /home/seb/Projets/OctaneGUI/Source/OctaneGUI/Application.cpp:27:
/home/seb/Projets/OctaneGUI/Source/OctaneGUI/Application.h:429:10: error: private field 'm_IgnoreModals' is not used [-Werror,-Wunused-private-field]
    bool m_IgnoreModals { false };
         ^
1 error generated.
make[2]: *** [Source/OctaneGUI/CMakeFiles/OctaneGUI.dir/build.make:636: Source/OctaneGUI/CMakeFiles/OctaneGUI.dir/Application.cpp.o] Error 1
```

3- In the Application.h file, I enclose the 'm_IgnoreModals' field with the 'TOOLS' macro, despite the comments indicating that the issue is known.
Compilation then proceeds without error, and the test applications appear to work as expected.

**Comment by mdavisprog** [comment]
Hi @seb777, thanks for the report. I'll have a look at this issue and have a fix for it in the next update.
