### ISSUE TITLE
Tree Control: not de-selecting children on collapse

### ISSUE THREAD

**Issue by thnom** [mdavisprog/OctaneGUI#6]
As video below, selecting Sub-Child 1 (child of Root1/Child1) and then hiding both (in sequence or not, same outcome) results in a selection of a non-existent child. Video also shows objects shape moving with each collapse. Have had a look and can see `m_Item->SetToggle(m_Expand);` within `Tree.cpp`, but don't think that's looking down the tree.

https://user-images.githubusercontent.com/56652672/184712346-40b930d1-a2ff-46cc-834f-333bc2db161e.mov

Edit: this is Metal/SDL2

**Comment by mdavisprog** [comment]
Thanks for pointing this out. I was able to reproduce this myself. I'm thinking there needs to be a check to see if the tree that is being collapsed contains the selected item and if so, set the selection to null.

**Comment by thnom** [comment]
Yeh I was looking at doing this but I'm still learning C++ and your API so wasn't sure if I was missing the obvious. I shall take a look and see if can resolve

**Comment by thnom** [comment]
Think something along the lines of https://github.com/thnom/OctaneGUI/commit/35fab50fce8f07edd940c5ed0e97c4c6f7a5e594 should work, but the selected isn't working. Will continue to take a look unless you resolve before I get there

**Comment by mdavisprog** [comment]
I took a peek at what might be causing the selection to render and I think the culprit may be in Tree::IsHidden function. The Tree::OnPaint function will paint the selection rectangle if the selected item is not hidden:

```c++
    if (Selected && !IsHidden(Selected))
    {
        PaintSelection(Brush, Selected);
    }
```

I recommend looking in the IsHidden function to see why the selected item is not found in any of the children of the tree.

**Comment by thnom** [comment]
Done a little digging and solved it. The below code (within `Tree:IsHidden` as you so kindly pointed out) is the culprit, changing `HasControl()` to `HasControlRecurse()` fixes the issue. I'll make the change with a fresh branch/pull request.

```
    if (m_List->HasControl(Item))
    {
        return !m_Expand;
    }
```

Below is my exploratory screenshots, you can see why the Recurse is required to find that control (at the very bottom buried in a couple of layers).

**`Item`**
<img width="741" alt="Screenshot 2022-08-18 at 20 46 21" src="https://user-images.githubusercontent.com/56652672/185481741-445e3608-de1d-40ea-a8d8-6d2d3e41e8d4.png">

**`m_Controls`**
<img width="1118" alt="Screenshot 2022-08-18 at 20 50 46" src="https://user-images.githubusercontent.com/56652672/185482386-f66e63f6-47b9-416b-86ec-18197d637c95.png">

Off-topic but saves a fresh issue pre-merge,
I pulled your system_file_dialogue branch and had to add the cocoa framework to make it compile (added in Xcode). I assume it will be the same as the foundation framework in terms of the CMake fix.

**Comment by mdavisprog** [comment]
Thanks for pointing out the issue for the 'system_file_dialog' branch. I'll be sure to add the framework before merging the branch.

I am wondering if with the change to use HasControlRecurse() if we can get rid of the following loop since it kind of does the same thing.

```c++
    for (const std::shared_ptr<Control>& Child : m_List->Controls())
    {
        const std::shared_ptr<Tree>& ChildTree = std::static_pointer_cast<Tree>(Child);

        if (ChildTree->IsHidden(Item))
        {
            return true;
        }
    }
```

Thanks for looking into this issue.

**Comment by thnom** [comment]
I had a look at this as that made sense but taking that out leaves the issue as-was. Presumably the first go round is fine, but when it recursively calls `IsHidden()`, it then meets `if (m_List->HasControlRecurse(Item))`, thus not painting.

Feels like an optimisation could be made, though.
