### ISSUE TITLE
Compiling via bash script results in failing executable

### ISSUE THREAD

**Issue by thnom** [mdavisprog/OctaneGUI#8]
Looking to try and use the tools as part of any build, but can't seem to get working via Xcode and bash script creates unix make files rather than an Xcode project. When compiling via bash script, `sh build.sh`, the executable fails to open with the following:
```
/Users/thnom/Projects/OctaneGUI/bin/Overview ; exit;                            
thnom@Thomass-MBP ~ % /Users/thnom/Projects/OctaneGUI/bin/Overview ; exit;
Using SDL version 2.0.22
libc++abi: terminating with uncaught exception of type std::out_of_range: unordered_map::at: key not found
zsh: abort      /Users/thnom/Projects/OctaneGUI/bin/Overview

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...      20 completed.
```

Ultimately I'd like to build in Xcode with tools enabled if that's easy enough, though..

**Comment by mdavisprog** [comment]
It seems the application does try to run as the SDL version is printed, but it could have failed to load a file. One thing that is not mentioned in the documentation currently is that the apps must be run from the same folder as the application. Make sure to change into the 'bin' directory before running the 'Overview' app.

I don't have much experience with XCode currently, but would like to support generating project files for them.

**Comment by thnom** [comment]
I was running it via just double-clicking but tried via:
```
cd bin
Open Overview
```
and got:
```
/Users/thnom/Projects/OctaneGUI/bin/Overview ; exit;                            
thnom@Thomass-MBP ~ % /Users/thnom/Projects/OctaneGUI/bin/Overview ; exit;
Using SDL version 2.0.22
Assertion failed: /Users/thnom/Projects/OctaneGUI/Source/OctaneGUI/Assert.cpp:51
Control with ID 'File.Quit' does not exist! Below is a list of existing IDs:

zsh: abort      /Users/thnom/Projects/OctaneGUI/bin/Overview

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```


Different error, I suspected the JSON wasn't being found but `Overview.json` is in that directory so not entirely sure.

Re: _I don't have much experience with XCode currently, but would like to support generating project files for them._, I took a look at your bash script and it looks like it is ready for them, not sure entirely what it is expecting to trigger it, though. To create Xcode, you run (from /Build/):
```
cmake -G Xcode  ..
```

Within `Generate.sh` you have:
```
if [[ ! -z $GENERATOR ]]; then
    CMAKE_OPTIONS="-G $GENERATOR"
fi
```
Not sure what the if statement means, but it feels like if it captures something specifically, it'll add the `-G Xcode` command.

**Comment by mdavisprog** [comment]
I just tried running the 'Overview' app with the 'open' command and was able to reproduce the issue. This is something I would like to resolve, but will take some time to investigate. I usually run the app by just calling the executable file like so:
```
./Overview
```
This should properly run the app in the bin directory and properly load the required files. Let me know if using this method does not work for you.

**Comment by thnom** [comment]
That works, but even when building Tools, they don't appear. Is there something I need to do to activate them?

**Comment by mdavisprog** [comment]
Glad that works for you. To get access to the various tools, you will need to open the command palette with the Ctrl+P key combination. I added documentation for the available tools to the [wiki](https://github.com/mdavisprog/OctaneGUI/wiki/Tools).

**Comment by thnom** [comment]
That's brilliant thank you. Closing issue with that additional doc and info in here..

**Comment by thnom** [comment]
Have a solution for building with Xcode project and Tools which may be worth documenting:

1. Build standard via scripts:
```
cd Scripts
sh build.sh Clean Tools
```
2. Navigate to Build path and remove CMake cache, and build Xcode project:
```
cd ../Build
rm -f "CMakeCache.txt"
cmake -G Xcode  ..
```
3. Within Xcode, navigate to Project settings:
<img width="1400" alt="Screenshot 2022-08-29 at 20 12 37" src="https://user-images.githubusercontent.com/56652672/187280031-9378eed3-11b9-4230-ab78-cfaa31804f8a.png">

4. Search for "preprocessor" and add tools:
<img width="906" alt="Screenshot 2022-08-29 at 20 14 26" src="https://user-images.githubusercontent.com/56652672/187280298-99e67b3f-fc1a-4faf-b75a-81671a6e4560.png">

**Comment by mdavisprog** [comment]
I looked into supporting building with Xcode and have pushed an update to the ```main``` branch. You can now run the Generate.sh script with Xcode as an argument and it will create the Xcode project. Also, you can also build the Xcode project with the Build.sh script as well in the terminal without opening the Xcode project if desired.

I took a look at the 'TOOLS' define and it is actually already defined, but it is defined in the OctaneGUI scheme. If you look at the build settings for that scheme, you should see 'TOOLS=1' defined in there.
